2025-06-24 13:14:35,142 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 13:16:26,729 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 13:17:18,087 - backendlogger - INFO - data
2025-06-24 13:17:18,276 - backendlogger - INFO - data
2025-06-24 13:17:19,122 - backendlogger - INFO - data
2025-06-24 13:25:41,087 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 13:30:13,054 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 13:34:02,568 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 13:42:33,320 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 13:44:58,015 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 13:45:18,688 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 13:48:02,692 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 13:48:37,503 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 13:51:16,617 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 13:56:35,208 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 13:59:30,244 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 14:01:12,158 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 14:04:57,464 - server - ERROR - Exception on request POST /webhook
Traceback (most recent call last):
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1464, in handle_request
    return await self.full_dispatch_request(request_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1502, in full_dispatch_request
    result = await self.handle_user_exception(error)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1059, in handle_user_exception
    raise error
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1500, in full_dispatch_request
    result = await self.dispatch_request(request_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1597, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/src/api_payments/payments.py", line 38, in webhook
    event = data["meta"]["event_name"]
            ~~~~^^^^^^^^
KeyError: 'meta'
2025-06-24 14:05:04,206 - server - ERROR - Exception on request POST /webhook
Traceback (most recent call last):
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1464, in handle_request
    return await self.full_dispatch_request(request_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1502, in full_dispatch_request
    result = await self.handle_user_exception(error)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1059, in handle_user_exception
    raise error
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1500, in full_dispatch_request
    result = await self.dispatch_request(request_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1597, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/src/api_payments/payments.py", line 38, in webhook
    event = data["meta"]["event_name"]
            ~~~~^^^^^^^^
KeyError: 'meta'
2025-06-24 14:05:22,327 - server - ERROR - Exception on request POST /webhook
Traceback (most recent call last):
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1464, in handle_request
    return await self.full_dispatch_request(request_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1502, in full_dispatch_request
    result = await self.handle_user_exception(error)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1059, in handle_user_exception
    raise error
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1500, in full_dispatch_request
    result = await self.dispatch_request(request_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1597, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/src/api_payments/payments.py", line 38, in webhook
    event = data["meta"]["event_name"]
            ~~~~^^^^^^^^
KeyError: 'meta'
2025-06-24 14:05:25,395 - server - ERROR - Exception on request POST /webhook
Traceback (most recent call last):
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1464, in handle_request
    return await self.full_dispatch_request(request_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1502, in full_dispatch_request
    result = await self.handle_user_exception(error)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1059, in handle_user_exception
    raise error
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1500, in full_dispatch_request
    result = await self.dispatch_request(request_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1597, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/src/api_payments/payments.py", line 38, in webhook
    event = data["meta"]["event_name"]
            ~~~~^^^^^^^^
KeyError: 'meta'
2025-06-24 14:05:28,487 - server - ERROR - Exception on request POST /webhook
Traceback (most recent call last):
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1464, in handle_request
    return await self.full_dispatch_request(request_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1502, in full_dispatch_request
    result = await self.handle_user_exception(error)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1059, in handle_user_exception
    raise error
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1500, in full_dispatch_request
    result = await self.dispatch_request(request_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1597, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/src/api_payments/payments.py", line 38, in webhook
    event = data["meta"]["event_name"]
            ~~~~^^^^^^^^
KeyError: 'meta'
2025-06-24 14:05:30,930 - server - ERROR - Exception on request POST /webhook
Traceback (most recent call last):
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1464, in handle_request
    return await self.full_dispatch_request(request_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1502, in full_dispatch_request
    result = await self.handle_user_exception(error)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1059, in handle_user_exception
    raise error
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1500, in full_dispatch_request
    result = await self.dispatch_request(request_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1597, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/src/api_payments/payments.py", line 38, in webhook
    event = data["meta"]["event_name"]
            ~~~~^^^^^^^^
KeyError: 'meta'
2025-06-24 14:05:31,544 - server - ERROR - Exception on request POST /webhook
Traceback (most recent call last):
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1464, in handle_request
    return await self.full_dispatch_request(request_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1502, in full_dispatch_request
    result = await self.handle_user_exception(error)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1059, in handle_user_exception
    raise error
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1500, in full_dispatch_request
    result = await self.dispatch_request(request_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1597, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/src/api_payments/payments.py", line 38, in webhook
    event = data["meta"]["event_name"]
            ~~~~^^^^^^^^
KeyError: 'meta'
2025-06-24 14:05:54,567 - server - ERROR - Exception on request POST /webhook
Traceback (most recent call last):
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1464, in handle_request
    return await self.full_dispatch_request(request_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1502, in full_dispatch_request
    result = await self.handle_user_exception(error)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1059, in handle_user_exception
    raise error
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1500, in full_dispatch_request
    result = await self.dispatch_request(request_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1597, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/src/api_payments/payments.py", line 38, in webhook
    event = data["meta"]["event_name"]
            ~~~~^^^^^^^^
KeyError: 'meta'
2025-06-24 14:05:57,279 - server - ERROR - Exception on request POST /webhook
Traceback (most recent call last):
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1464, in handle_request
    return await self.full_dispatch_request(request_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1502, in full_dispatch_request
    result = await self.handle_user_exception(error)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1059, in handle_user_exception
    raise error
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1500, in full_dispatch_request
    result = await self.dispatch_request(request_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1597, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/src/api_payments/payments.py", line 38, in webhook
    event = data["meta"]["event_name"]
            ~~~~^^^^^^^^
KeyError: 'meta'
2025-06-24 14:07:43,230 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 14:07:47,920 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 14:07:53,035 - server - ERROR - Exception on request POST /webhook
Traceback (most recent call last):
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1464, in handle_request
    return await self.full_dispatch_request(request_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1502, in full_dispatch_request
    result = await self.handle_user_exception(error)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1059, in handle_user_exception
    raise error
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1500, in full_dispatch_request
    result = await self.dispatch_request(request_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1597, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/src/api_payments/payments.py", line 38, in webhook
    event = data["data"]["meta"]["event_name"]
            ~~~~^^^^^^^^
KeyError: 'data'
2025-06-24 14:07:58,759 - server - ERROR - Exception on request POST /webhook
Traceback (most recent call last):
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1464, in handle_request
    return await self.full_dispatch_request(request_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1502, in full_dispatch_request
    result = await self.handle_user_exception(error)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1059, in handle_user_exception
    raise error
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1500, in full_dispatch_request
    result = await self.dispatch_request(request_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1597, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/src/api_payments/payments.py", line 38, in webhook
    event = data["data"]["meta"]["event_name"]
            ~~~~^^^^^^^^
KeyError: 'data'
2025-06-24 14:08:14,602 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 14:08:19,353 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 14:08:21,506 - backendlogger - INFO - data
2025-06-24 14:08:24,473 - backendlogger - INFO - data
2025-06-24 14:08:40,059 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 14:08:44,252 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 14:08:47,059 - backendlogger - INFO - data
2025-06-24 14:08:56,057 - backendlogger - INFO - data
2025-06-24 14:09:34,207 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 14:09:50,796 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 14:09:55,068 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 14:09:57,560 - backendlogger - INFO - data
2025-06-24 14:10:47,022 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 14:11:01,647 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 14:11:14,781 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 14:11:30,085 - backendlogger - INFO - data
2025-06-24 14:12:40,015 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 14:13:10,746 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 14:14:20,867 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 14:14:24,278 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 14:14:30,230 - backendlogger - INFO - data
2025-06-24 14:14:57,127 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 14:15:37,225 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 14:15:56,643 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 14:18:17,544 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 14:23:14,702 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 14:23:23,900 - backendlogger - INFO - data
2025-06-24 14:25:08,289 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 14:25:25,936 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 14:26:14,890 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 14:26:16,394 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 14:26:23,835 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 14:26:33,603 - backendlogger - INFO - data
2025-06-24 14:28:41,669 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 14:29:02,854 - backendlogger - INFO - data
2025-06-24 14:29:37,721 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 14:29:44,823 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 14:29:49,330 - backendlogger - INFO - data
2025-06-24 14:30:03,508 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 14:30:07,827 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 14:30:09,559 - backendlogger - INFO - data
2025-06-24 14:30:32,543 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 14:30:39,832 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 14:30:42,607 - server - ERROR - Exception on request POST /webhook
Traceback (most recent call last):
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1464, in handle_request
    return await self.full_dispatch_request(request_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1502, in full_dispatch_request
    result = await self.handle_user_exception(error)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1059, in handle_user_exception
    raise error
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1500, in full_dispatch_request
    result = await self.dispatch_request(request_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1597, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/src/api_payments/payments.py", line 50, in webhook
    await HANDLERS[event_name](rq)
  File "/home/peter/Code/quartApp/src/api_payments/payments.py", line 21, in subscription_created
    status = data["status"]
             ~~~~^^^^^^^^^^
KeyError: 'status'
2025-06-24 14:30:48,323 - server - ERROR - Exception on request POST /webhook
Traceback (most recent call last):
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1464, in handle_request
    return await self.full_dispatch_request(request_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1502, in full_dispatch_request
    result = await self.handle_user_exception(error)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1059, in handle_user_exception
    raise error
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1500, in full_dispatch_request
    result = await self.dispatch_request(request_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1597, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/src/api_payments/payments.py", line 50, in webhook
    await HANDLERS[event_name](rq)
  File "/home/peter/Code/quartApp/src/api_payments/payments.py", line 21, in subscription_created
    status = data["status"]
             ~~~~^^^^^^^^^^
KeyError: 'status'
2025-06-24 14:31:14,031 - server - ERROR - Exception on request POST /webhook
Traceback (most recent call last):
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1464, in handle_request
    return await self.full_dispatch_request(request_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1502, in full_dispatch_request
    result = await self.handle_user_exception(error)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1059, in handle_user_exception
    raise error
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1500, in full_dispatch_request
    result = await self.dispatch_request(request_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1597, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/src/api_payments/payments.py", line 50, in webhook
    await HANDLERS[event_name](rq)
  File "/home/peter/Code/quartApp/src/api_payments/payments.py", line 21, in subscription_created
    status = data["status"]
             ~~~~^^^^^^^^^^
KeyError: 'status'
2025-06-24 14:31:32,791 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 14:31:36,916 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 14:31:42,265 - server - ERROR - Exception on request POST /webhook
Traceback (most recent call last):
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1464, in handle_request
    return await self.full_dispatch_request(request_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1502, in full_dispatch_request
    result = await self.handle_user_exception(error)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1059, in handle_user_exception
    raise error
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1500, in full_dispatch_request
    result = await self.dispatch_request(request_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1597, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/src/api_payments/payments.py", line 50, in webhook
    await HANDLERS[event_name](rq)
  File "/home/peter/Code/quartApp/src/api_payments/payments.py", line 22, in subscription_created
    paddle_subscription_id = data["first_subscription_item"]["subscription_id"]
                             ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'first_subscription_item'
2025-06-24 14:31:48,012 - server - ERROR - Exception on request POST /webhook
Traceback (most recent call last):
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1464, in handle_request
    return await self.full_dispatch_request(request_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1502, in full_dispatch_request
    result = await self.handle_user_exception(error)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1059, in handle_user_exception
    raise error
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1500, in full_dispatch_request
    result = await self.dispatch_request(request_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1597, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/src/api_payments/payments.py", line 50, in webhook
    await HANDLERS[event_name](rq)
  File "/home/peter/Code/quartApp/src/api_payments/payments.py", line 22, in subscription_created
    paddle_subscription_id = data["first_subscription_item"]["subscription_id"]
                             ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'first_subscription_item'
2025-06-24 14:32:13,814 - server - ERROR - Exception on request POST /webhook
Traceback (most recent call last):
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1464, in handle_request
    return await self.full_dispatch_request(request_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1502, in full_dispatch_request
    result = await self.handle_user_exception(error)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1059, in handle_user_exception
    raise error
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1500, in full_dispatch_request
    result = await self.dispatch_request(request_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1597, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/src/api_payments/payments.py", line 50, in webhook
    await HANDLERS[event_name](rq)
  File "/home/peter/Code/quartApp/src/api_payments/payments.py", line 22, in subscription_created
    paddle_subscription_id = data["first_subscription_item"]["subscription_id"]
                             ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'first_subscription_item'
2025-06-24 14:32:16,844 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 14:32:33,502 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 14:32:36,812 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 14:32:46,188 - backendlogger - INFO - Database connection pool created
2025-06-24 14:32:46,190 - backendlogger - ERROR - Error inserting subscription: invalid input for query argument $1: 'testid' (invalid UUID 'testid': length must be between 32..36 characters, got 6)
2025-06-24 14:32:46,194 - backendlogger - INFO - data
2025-06-24 14:33:23,343 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 14:33:34,517 - backendlogger - INFO - Database connection pool created
2025-06-24 14:33:34,519 - backendlogger - ERROR - Error inserting subscription: invalid input for query argument $1: 'testid' (invalid UUID 'testid': length must be between 32..36 characters, got 6)
2025-06-24 14:33:34,523 - backendlogger - INFO - data
2025-06-24 14:33:41,160 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 14:34:42,214 - backendlogger - INFO - Database connection pool created
2025-06-24 14:34:42,217 - backendlogger - ERROR - Error inserting subscription: invalid input for query argument $2: 557861 ('int' object has no attribute 'bytes')
2025-06-24 14:34:42,223 - backendlogger - INFO - data
2025-06-24 14:34:42,320 - backendlogger - INFO - data
2025-06-24 14:35:11,689 - backendlogger - INFO - data
2025-06-24 14:35:30,589 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 14:35:33,452 - backendlogger - INFO - Database connection pool created
2025-06-24 14:35:33,454 - backendlogger - ERROR - Error inserting subscription: invalid input for query argument $1: 'testid' (invalid UUID 'testid': length must be between 32..36 characters, got 6)
2025-06-24 14:35:33,458 - backendlogger - INFO - data
2025-06-24 14:36:17,109 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 14:37:24,245 - backendlogger - INFO - data
2025-06-24 14:37:24,556 - backendlogger - INFO - Database connection pool created
2025-06-24 14:37:24,557 - backendlogger - ERROR - Error inserting subscription: invalid input for query argument $2: 557861 ('int' object has no attribute 'bytes')
2025-06-24 14:37:24,559 - backendlogger - INFO - data
2025-06-24 14:37:53,111 - backendlogger - INFO - data
2025-06-24 14:38:32,810 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 14:38:51,614 - backendlogger - INFO - Database connection pool created
2025-06-24 14:38:51,616 - backendlogger - ERROR - Error inserting subscription: invalid input for query argument $2: 557861 ('int' object has no attribute 'bytes')
2025-06-24 14:38:51,616 - backendlogger - INFO - data
2025-06-24 14:40:15,171 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 14:40:29,766 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 14:40:44,193 - backendlogger - INFO - Database connection pool created
2025-06-24 14:40:44,195 - backendlogger - ERROR - Error inserting subscription: invalid input for query argument $2: '557861' (invalid UUID '557861': length must be between 32..36 characters, got 6)
2025-06-24 14:40:44,195 - backendlogger - INFO - data
2025-06-24 14:44:00,159 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 14:44:06,691 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 14:44:23,991 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 14:45:58,985 - server - ERROR - Exception on request POST /webhook
Traceback (most recent call last):
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1464, in handle_request
    return await self.full_dispatch_request(request_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1502, in full_dispatch_request
    result = await self.handle_user_exception(error)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1059, in handle_user_exception
    raise error
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1500, in full_dispatch_request
    result = await self.dispatch_request(request_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1597, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/src/api_payments/payments.py", line 54, in webhook
    await HANDLERS[event_name](rq)
  File "/home/peter/Code/quartApp/src/api_payments/payments.py", line 20, in subscription_created
    plan_id = meta["custom_data"]["plan_id"]
              ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'plan_id'
2025-06-24 14:46:00,298 - backendlogger - INFO - data
2025-06-24 14:46:04,662 - server - ERROR - Exception on request POST /webhook
Traceback (most recent call last):
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1464, in handle_request
    return await self.full_dispatch_request(request_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1502, in full_dispatch_request
    result = await self.handle_user_exception(error)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1059, in handle_user_exception
    raise error
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1500, in full_dispatch_request
    result = await self.dispatch_request(request_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1597, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/src/api_payments/payments.py", line 54, in webhook
    await HANDLERS[event_name](rq)
  File "/home/peter/Code/quartApp/src/api_payments/payments.py", line 20, in subscription_created
    plan_id = meta["custom_data"]["plan_id"]
              ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'plan_id'
2025-06-24 14:46:28,760 - backendlogger - INFO - data
2025-06-24 14:46:30,359 - server - ERROR - Exception on request POST /webhook
Traceback (most recent call last):
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1464, in handle_request
    return await self.full_dispatch_request(request_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1502, in full_dispatch_request
    result = await self.handle_user_exception(error)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1059, in handle_user_exception
    raise error
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1500, in full_dispatch_request
    result = await self.dispatch_request(request_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1597, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/src/api_payments/payments.py", line 54, in webhook
    await HANDLERS[event_name](rq)
  File "/home/peter/Code/quartApp/src/api_payments/payments.py", line 20, in subscription_created
    plan_id = meta["custom_data"]["plan_id"]
              ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'plan_id'
2025-06-24 14:48:48,013 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 14:49:00,931 - server - ERROR - Exception on request POST /webhook
Traceback (most recent call last):
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1464, in handle_request
    return await self.full_dispatch_request(request_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1502, in full_dispatch_request
    result = await self.handle_user_exception(error)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1059, in handle_user_exception
    raise error
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1500, in full_dispatch_request
    result = await self.dispatch_request(request_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1597, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/src/api_payments/payments.py", line 54, in webhook
    await HANDLERS[event_name](rq)
  File "/home/peter/Code/quartApp/src/api_payments/payments.py", line 20, in subscription_created
    plan_id = meta["custom_data"]["plan_id"]
              ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'plan_id'
2025-06-24 14:49:01,157 - backendlogger - INFO - data
2025-06-24 14:49:06,777 - server - ERROR - Exception on request POST /webhook
Traceback (most recent call last):
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1464, in handle_request
    return await self.full_dispatch_request(request_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1502, in full_dispatch_request
    result = await self.handle_user_exception(error)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1059, in handle_user_exception
    raise error
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1500, in full_dispatch_request
    result = await self.dispatch_request(request_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1597, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/src/api_payments/payments.py", line 54, in webhook
    await HANDLERS[event_name](rq)
  File "/home/peter/Code/quartApp/src/api_payments/payments.py", line 20, in subscription_created
    plan_id = meta["custom_data"]["plan_id"]
              ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'plan_id'
2025-06-24 14:49:30,554 - backendlogger - INFO - data
2025-06-24 14:49:33,359 - server - ERROR - Exception on request POST /webhook
Traceback (most recent call last):
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1464, in handle_request
    return await self.full_dispatch_request(request_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1502, in full_dispatch_request
    result = await self.handle_user_exception(error)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1059, in handle_user_exception
    raise error
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1500, in full_dispatch_request
    result = await self.dispatch_request(request_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1597, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/src/api_payments/payments.py", line 54, in webhook
    await HANDLERS[event_name](rq)
  File "/home/peter/Code/quartApp/src/api_payments/payments.py", line 20, in subscription_created
    plan_id = meta["custom_data"]["plan_id"]
              ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'plan_id'
2025-06-24 14:50:01,527 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 14:51:32,655 - server - ERROR - Exception on request POST /webhook
Traceback (most recent call last):
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1464, in handle_request
    return await self.full_dispatch_request(request_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1502, in full_dispatch_request
    result = await self.handle_user_exception(error)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1059, in handle_user_exception
    raise error
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1500, in full_dispatch_request
    result = await self.dispatch_request(request_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1597, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/src/api_payments/payments.py", line 54, in webhook
    await HANDLERS[event_name](rq)
  File "/home/peter/Code/quartApp/src/api_payments/payments.py", line 20, in subscription_created
    plan_id = meta["custom_data"]["plan_id"]
              ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'plan_id'
2025-06-24 14:51:32,836 - backendlogger - INFO - data
2025-06-24 14:51:38,741 - server - ERROR - Exception on request POST /webhook
Traceback (most recent call last):
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1464, in handle_request
    return await self.full_dispatch_request(request_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1502, in full_dispatch_request
    result = await self.handle_user_exception(error)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1059, in handle_user_exception
    raise error
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1500, in full_dispatch_request
    result = await self.dispatch_request(request_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1597, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/src/api_payments/payments.py", line 54, in webhook
    await HANDLERS[event_name](rq)
  File "/home/peter/Code/quartApp/src/api_payments/payments.py", line 20, in subscription_created
    plan_id = meta["custom_data"]["plan_id"]
              ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'plan_id'
2025-06-24 14:51:59,128 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 14:52:02,172 - backendlogger - INFO - data
2025-06-24 14:52:05,242 - server - ERROR - Exception on request POST /webhook
Traceback (most recent call last):
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1464, in handle_request
    return await self.full_dispatch_request(request_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1502, in full_dispatch_request
    result = await self.handle_user_exception(error)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1059, in handle_user_exception
    raise error
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1500, in full_dispatch_request
    result = await self.dispatch_request(request_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/.venv/lib64/python3.13/site-packages/quart/app.py", line 1597, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Code/quartApp/src/api_payments/payments.py", line 54, in webhook
    await HANDLERS[event_name](rq)
  File "/home/peter/Code/quartApp/src/api_payments/payments.py", line 20, in subscription_created
    plan_id = meta["custom_data"]["plan_id"]
              ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'plan_id'
2025-06-24 14:54:12,767 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 14:56:04,787 - backendlogger - INFO - Database connection pool created
2025-06-24 14:56:04,789 - backendlogger - ERROR - Error inserting subscription: invalid input for query argument $6: '2025-07-24T11:55:55.000000Z' (expected a datetime.date or datetime.datetime instance, got 'str')
2025-06-24 14:56:04,790 - backendlogger - INFO - data
2025-06-24 14:56:33,841 - backendlogger - INFO - data
2025-06-24 14:56:34,688 - backendlogger - INFO - data
2025-06-24 14:59:47,648 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 14:59:50,556 - backendlogger - INFO - Database connection pool created
2025-06-24 14:59:52,666 - backendlogger - INFO - data
2025-06-24 14:59:52,669 - backendlogger - INFO - data
2025-06-24 15:06:09,626 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 15:06:44,432 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 15:08:37,979 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 15:09:53,188 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 15:10:45,127 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 15:11:20,944 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 15:11:27,521 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 15:11:33,068 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 15:12:01,810 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 15:12:25,536 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 15:12:47,210 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 15:12:58,768 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 15:13:06,300 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 15:13:24,883 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 15:15:43,339 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 15:15:52,810 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 15:18:08,649 - backendlogger - INFO - data
2025-06-24 15:18:08,976 - backendlogger - INFO - Database connection pool created
2025-06-24 15:18:08,999 - backendlogger - ERROR - Error in db_cancel_subscription : invalid input for query argument $2: 1292827 (expected str, got int)
2025-06-24 15:18:08,999 - backendlogger - INFO - data
2025-06-24 15:18:09,216 - backendlogger - INFO - data
2025-06-24 15:18:33,698 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 15:18:38,922 - backendlogger - INFO - data
2025-06-24 15:18:39,117 - backendlogger - INFO - data
2025-06-24 15:18:40,857 - backendlogger - INFO - data
2025-06-24 15:18:46,200 - backendlogger - INFO - data
2025-06-24 15:18:46,201 - backendlogger - INFO - Database connection pool created
2025-06-24 15:18:46,364 - backendlogger - INFO - data
2025-06-24 15:18:47,305 - backendlogger - INFO - data
2025-06-24 15:19:59,977 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 15:21:12,142 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 15:21:30,751 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 15:22:02,517 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 15:22:42,304 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 15:23:14,080 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 15:23:38,778 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 15:24:29,745 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 15:25:23,712 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 15:25:56,498 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 15:27:45,019 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 15:27:57,603 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 15:28:20,280 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 15:28:35,005 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 15:29:09,282 - backendlogger - INFO - data
2025-06-24 15:29:09,585 - backendlogger - INFO - Database connection pool created
2025-06-24 15:29:09,587 - backendlogger - ERROR - Error in db_update_subscription: invalid input for query argument $5: 1292827 (expected str, got int)
2025-06-24 15:29:09,587 - backendlogger - INFO - data
2025-06-24 15:29:10,215 - backendlogger - ERROR - Error in db_update_subscription: invalid input for query argument $5: 1292827 (expected str, got int)
2025-06-24 15:29:10,216 - backendlogger - INFO - data
2025-06-24 15:29:40,028 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 15:29:46,873 - backendlogger - INFO - data
2025-06-24 15:29:47,397 - backendlogger - INFO - Database connection pool created
2025-06-24 15:29:47,621 - backendlogger - INFO - data
2025-06-24 15:29:47,998 - backendlogger - INFO - data
2025-06-24 15:57:41,719 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 15:57:57,322 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 15:58:04,861 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 15:58:15,432 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 15:58:34,037 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 15:58:52,690 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 15:59:36,617 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 16:00:13,392 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 20:07:08,347 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 20:08:53,456 - backendlogger - INFO - data
2025-06-24 20:10:51,390 - backendlogger - INFO - Database connection pool created
2025-06-24 20:10:51,565 - backendlogger - INFO - data
2025-06-24 20:11:38,791 - backendlogger - INFO - data
2025-06-24 20:19:02,077 - backendlogger - ERROR - Error in db_mark_subscription_expired : syntax error at or near "WHERE"
2025-06-24 20:19:02,077 - backendlogger - INFO - data
2025-06-24 20:19:58,282 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 20:20:06,420 - backendlogger - INFO - Database connection pool created
2025-06-24 20:20:06,422 - backendlogger - ERROR - Error in db_mark_subscription_expired : the server expects 3 arguments for this query, 2 were passed
HINT:  Check the query against the passed list of arguments.
2025-06-24 20:20:06,422 - backendlogger - INFO - data
2025-06-24 20:21:14,608 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 20:21:26,209 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 20:21:38,638 - backendlogger - INFO - Database connection pool created
2025-06-24 20:21:38,814 - backendlogger - INFO - data
2025-06-24 20:22:23,508 - backendlogger - INFO - data
2025-06-24 20:28:28,334 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 20:29:04,820 - backendlogger - INFO - Database connection pool created
2025-06-24 20:29:05,060 - backendlogger - INFO - data
2025-06-24 20:29:51,833 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 20:30:12,108 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 20:30:22,946 - backendlogger - INFO - Database connection pool created
2025-06-24 20:30:23,497 - backendlogger - INFO - data
2025-06-24 20:31:12,176 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 20:31:22,057 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 20:52:27,309 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 20:52:34,056 - backendlogger - INFO - subscription_paused
2025-06-24 20:52:34,363 - backendlogger - INFO - Database connection pool created
2025-06-24 20:52:34,547 - backendlogger - INFO - data
2025-06-24 20:54:37,769 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 20:56:16,656 - backendlogger - INFO - subscription_expired
2025-06-24 20:56:16,946 - backendlogger - INFO - Database connection pool created
2025-06-24 20:56:17,144 - backendlogger - INFO - data
2025-06-24 20:56:43,609 - backendlogger - INFO - subscription_cancelled
2025-06-24 20:56:43,780 - backendlogger - INFO - data
2025-06-24 20:56:57,948 - backendlogger - INFO - subscription_resumed
2025-06-24 20:56:57,948 - backendlogger - INFO - data
2025-06-24 20:57:20,737 - backendlogger - INFO - subscription_updated
2025-06-24 20:57:20,947 - backendlogger - INFO - data
2025-06-24 21:53:13,034 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 21:54:06,103 - backendlogger - INFO - subscription_created
2025-06-24 21:54:06,498 - backendlogger - INFO - Database connection pool created
2025-06-24 21:54:10,908 - backendlogger - INFO - Subscription created successfully for user_id: f7d8d7c7-a169-4dfa-8913-d68a4132290b
2025-06-24 21:54:10,908 - backendlogger - INFO - data
2025-06-24 21:56:58,974 - backendlogger - INFO - subscription_created
2025-06-24 21:56:59,355 - backendlogger - INFO - Subscription created successfully for user_id: f7d8d7c7-a169-4dfa-8913-d68a4132290b
2025-06-24 21:56:59,355 - backendlogger - INFO - data
2025-06-24 21:58:58,724 - backendlogger - INFO - subscription_created
2025-06-24 21:58:59,121 - backendlogger - INFO - Subscription created successfully for user_id: f7d8d7c7-a169-4dfa-8913-d68a4132290b
2025-06-24 21:58:59,122 - backendlogger - INFO - data
2025-06-24 22:00:09,080 - backendlogger - INFO - subscription_created
2025-06-24 22:00:09,495 - backendlogger - INFO - Subscription created successfully for user_id: f7d8d7c7-a169-4dfa-8913-d68a4132290b
2025-06-24 22:00:09,495 - backendlogger - INFO - data
2025-06-24 22:00:26,918 - backendlogger - INFO - subscription_resumed
2025-06-24 22:00:26,918 - backendlogger - INFO - data
2025-06-24 22:00:47,614 - backendlogger - INFO - subscription_updated
2025-06-24 22:00:48,020 - backendlogger - INFO - Subscription updated successfully for user_id: f7d8d7c7-a169-4dfa-8913-d68a4132290b
2025-06-24 22:00:48,020 - backendlogger - INFO - data
2025-06-24 22:01:20,807 - backendlogger - INFO - subscription_cancelled
2025-06-24 22:01:21,066 - backendlogger - INFO - Subscription cancelled successfully for paddle_subscription_id: 1292827
2025-06-24 22:01:21,066 - backendlogger - INFO - data
2025-06-24 22:02:14,055 - backendlogger - INFO - subscription_unpaused
2025-06-24 22:02:14,055 - backendlogger - INFO - data
2025-06-24 22:02:20,392 - backendlogger - INFO - subscription_resumed
2025-06-24 22:02:20,392 - backendlogger - INFO - data
2025-06-24 22:02:27,776 - backendlogger - INFO - subscription_unpaused
2025-06-24 22:02:27,776 - backendlogger - INFO - data
2025-06-24 22:02:56,679 - backendlogger - INFO - subscription_resumed
2025-06-24 22:02:56,679 - backendlogger - INFO - data
2025-06-24 22:04:47,038 - backendlogger - INFO - subscription_created
2025-06-24 22:04:47,328 - backendlogger - INFO - Subscription created successfully for user_id: f7d8d7c7-a169-4dfa-8913-d68a4132290b
2025-06-24 22:04:47,337 - backendlogger - INFO - data
2025-06-24 22:04:47,383 - backendlogger - INFO - subscription_payment_success
2025-06-24 22:04:47,383 - backendlogger - INFO - data
2025-06-24 22:05:16,378 - backendlogger - INFO - subscription_updated
2025-06-24 22:05:16,656 - backendlogger - INFO - Subscription updated successfully for user_id: f7d8d7c7-a169-4dfa-8913-d68a4132290b
2025-06-24 22:05:16,656 - backendlogger - INFO - data
2025-06-24 22:05:33,857 - backendlogger - INFO - subscription_paused
2025-06-24 22:05:33,857 - backendlogger - INFO - subscription_updated
2025-06-24 22:05:34,482 - backendlogger - INFO - Subscription paused successfully for paddle_subscription_id: 1293604
2025-06-24 22:05:34,482 - backendlogger - INFO - data
2025-06-24 22:05:34,864 - backendlogger - INFO - Subscription updated successfully for user_id: f7d8d7c7-a169-4dfa-8913-d68a4132290b
2025-06-24 22:05:34,864 - backendlogger - INFO - data
2025-06-24 22:05:35,280 - backendlogger - INFO - subscription_updated
2025-06-24 22:05:39,331 - backendlogger - INFO - Subscription updated successfully for user_id: f7d8d7c7-a169-4dfa-8913-d68a4132290b
2025-06-24 22:05:39,331 - backendlogger - INFO - data
2025-06-24 22:05:59,645 - backendlogger - INFO - subscription_updated
2025-06-24 22:05:59,645 - backendlogger - INFO - subscription_unpaused
2025-06-24 22:05:59,646 - backendlogger - INFO - data
2025-06-24 22:05:59,956 - backendlogger - INFO - Subscription updated successfully for user_id: f7d8d7c7-a169-4dfa-8913-d68a4132290b
2025-06-24 22:05:59,956 - backendlogger - INFO - data
2025-06-24 22:06:00,643 - backendlogger - INFO - subscription_updated
2025-06-24 22:06:00,867 - backendlogger - INFO - Subscription updated successfully for user_id: f7d8d7c7-a169-4dfa-8913-d68a4132290b
2025-06-24 22:06:00,867 - backendlogger - INFO - data
2025-06-24 22:07:29,253 - backendlogger - INFO - subscription_created
2025-06-24 22:07:29,587 - backendlogger - INFO - subscription_payment_success
2025-06-24 22:07:29,588 - backendlogger - INFO - data
2025-06-24 22:07:32,250 - backendlogger - INFO - Subscription created successfully for user_id: f7d8d7c7-a169-4dfa-8913-d68a4132290b
2025-06-24 22:07:32,251 - backendlogger - INFO - data
2025-06-24 22:07:58,741 - backendlogger - INFO - subscription_updated
2025-06-24 22:07:59,076 - backendlogger - INFO - Subscription updated successfully for user_id: f7d8d7c7-a169-4dfa-8913-d68a4132290b
2025-06-24 22:07:59,076 - backendlogger - INFO - data
2025-06-24 22:09:33,873 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 22:10:40,229 - backendlogger - INFO - subscription_created
2025-06-24 22:10:40,537 - backendlogger - INFO - subscription_payment_success
2025-06-24 22:10:40,537 - backendlogger - INFO - data
2025-06-24 22:10:40,539 - backendlogger - INFO - Database connection pool created
2025-06-24 22:10:40,719 - backendlogger - INFO - Subscription created successfully for user_id: f7d8d7c7-a169-4dfa-8913-d68a4132290b
2025-06-24 22:10:40,720 - backendlogger - INFO - data
2025-06-24 22:12:05,530 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 22:13:02,584 - backendlogger - INFO - subscription_updated
2025-06-24 22:13:02,946 - backendlogger - INFO - Database connection pool created
2025-06-24 22:13:03,236 - backendlogger - INFO - Subscription updated successfully for user_id: f7d8d7c7-a169-4dfa-8913-d68a4132290b
2025-06-24 22:13:03,236 - backendlogger - INFO - data
2025-06-24 22:17:22,801 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 22:17:31,244 - backendlogger - INFO - subscription_updated
2025-06-24 22:17:31,521 - backendlogger - INFO - Database connection pool created
2025-06-24 22:17:31,710 - backendlogger - INFO - Subscription updated successfully for user_id: f7d8d7c7-a169-4dfa-8913-d68a4132290b
2025-06-24 22:17:31,710 - backendlogger - INFO - data
2025-06-24 22:20:19,920 - backendlogger - INFO - subscription_created
2025-06-24 22:20:20,224 - backendlogger - INFO - Subscription created successfully for user_id: f7d8d7c7-a169-4dfa-8913-d68a4132290b
2025-06-24 22:20:20,224 - backendlogger - INFO - data
2025-06-24 22:20:47,773 - backendlogger - INFO - subscription_updated
2025-06-24 22:20:48,061 - backendlogger - INFO - Subscription updated successfully for user_id: f7d8d7c7-a169-4dfa-8913-d68a4132290b
2025-06-24 22:20:48,062 - backendlogger - INFO - data
2025-06-24 22:21:01,899 - backendlogger - INFO - subscription_cancelled
2025-06-24 22:21:02,184 - backendlogger - INFO - Subscription cancelled successfully for paddle_subscription_id: 1293614
2025-06-24 22:21:02,185 - backendlogger - INFO - data
2025-06-24 22:21:22,791 - backendlogger - INFO - subscription_resumed
2025-06-24 22:21:22,791 - backendlogger - INFO - data
2025-06-24 22:21:45,150 - backendlogger - INFO - subscription_updated
2025-06-24 22:21:45,464 - backendlogger - INFO - Subscription updated successfully for user_id: f7d8d7c7-a169-4dfa-8913-d68a4132290b
2025-06-24 22:21:45,464 - backendlogger - INFO - data
2025-06-24 22:22:02,894 - backendlogger - INFO - subscription_expired
2025-06-24 22:22:03,168 - backendlogger - INFO - Subscription expired successfully for paddle_subscription_id: 1293614
2025-06-24 22:22:03,168 - backendlogger - INFO - data
2025-06-24 22:22:18,016 - backendlogger - INFO - subscription_paused
2025-06-24 22:22:18,286 - backendlogger - INFO - Subscription paused successfully for paddle_subscription_id: 1293614
2025-06-24 22:22:18,286 - backendlogger - INFO - data
2025-06-24 22:22:25,254 - backendlogger - INFO - subscription_updated
2025-06-24 22:22:25,473 - backendlogger - INFO - Subscription updated successfully for user_id: f7d8d7c7-a169-4dfa-8913-d68a4132290b
2025-06-24 22:22:25,474 - backendlogger - INFO - data
2025-06-24 22:22:42,462 - backendlogger - INFO - subscription_paused
2025-06-24 22:22:42,717 - backendlogger - INFO - Subscription paused successfully for paddle_subscription_id: 1293614
2025-06-24 22:22:42,717 - backendlogger - INFO - data
2025-06-24 22:23:01,811 - backendlogger - INFO - subscription_paused
2025-06-24 22:23:02,057 - backendlogger - INFO - Subscription paused successfully for paddle_subscription_id: 1293614
2025-06-24 22:23:02,057 - backendlogger - INFO - data
2025-06-24 22:23:09,795 - backendlogger - INFO - subscription_unpaused
2025-06-24 22:23:09,795 - backendlogger - INFO - data
2025-06-24 22:23:30,686 - backendlogger - INFO - subscription_updated
2025-06-24 22:23:31,093 - backendlogger - INFO - Subscription updated successfully for user_id: f7d8d7c7-a169-4dfa-8913-d68a4132290b
2025-06-24 22:23:31,094 - backendlogger - INFO - data
2025-06-24 22:27:57,387 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 22:28:36,810 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 22:30:59,167 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 22:32:36,863 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 22:33:01,054 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 22:38:44,122 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 22:38:49,335 - backendlogger - INFO - subscription_updated
2025-06-24 22:38:49,913 - backendlogger - INFO - Database connection pool created
2025-06-24 22:38:51,622 - backendlogger - INFO - Subscription updated successfully for user_id: f7d8d7c7-a169-4dfa-8913-d68a4132290b
2025-06-24 22:38:51,622 - backendlogger - INFO - data
2025-06-24 22:39:43,233 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 22:39:51,805 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 22:40:08,503 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 22:40:22,823 - backendlogger - INFO - subscription_updated
2025-06-24 22:40:23,142 - backendlogger - INFO - Database connection pool created
2025-06-24 22:40:23,386 - backendlogger - INFO - Subscription updated successfully for user_id: f7d8d7c7-a169-4dfa-8913-d68a4132290b
2025-06-24 22:40:23,386 - backendlogger - INFO - data
2025-06-24 22:41:18,020 - backendlogger - INFO - subscription_paused
2025-06-24 22:41:18,221 - backendlogger - INFO - subscription_updated
2025-06-24 22:41:18,384 - backendlogger - INFO - Subscription paused successfully for paddle_subscription_id: 1293614
2025-06-24 22:41:18,385 - backendlogger - INFO - data
2025-06-24 22:41:18,601 - backendlogger - INFO - Subscription updated successfully for user_id: f7d8d7c7-a169-4dfa-8913-d68a4132290b
2025-06-24 22:41:18,601 - backendlogger - INFO - data
2025-06-24 22:41:19,557 - backendlogger - INFO - subscription_updated
2025-06-24 22:41:19,786 - backendlogger - INFO - Subscription updated successfully for user_id: f7d8d7c7-a169-4dfa-8913-d68a4132290b
2025-06-24 22:41:19,786 - backendlogger - INFO - data
2025-06-24 22:42:00,410 - backendlogger - INFO - subscription_resumed
2025-06-24 22:42:00,410 - backendlogger - INFO - data
2025-06-24 22:42:05,019 - backendlogger - INFO - subscription_updated
2025-06-24 22:42:05,493 - backendlogger - INFO - Subscription updated successfully for user_id: f7d8d7c7-a169-4dfa-8913-d68a4132290b
2025-06-24 22:42:05,494 - backendlogger - INFO - data
2025-06-24 22:43:31,973 - backendlogger - INFO - subscription_created
2025-06-24 22:43:35,070 - backendlogger - INFO - Subscription created successfully for user_id: f7d8d7c7-a169-4dfa-8913-d68a4132290b
2025-06-24 22:43:35,070 - backendlogger - INFO - data
2025-06-24 23:20:27,032 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 23:29:28,879 - hypercorn.error - INFO - Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-06-24 23:31:35,262 - backendlogger - INFO - subscription_created
2025-06-24 23:31:35,549 - backendlogger - INFO - Database connection pool created
2025-06-24 23:31:35,588 - backendlogger - INFO - subscription_payment_success
2025-06-24 23:31:35,588 - backendlogger - INFO - data
2025-06-24 23:31:35,805 - backendlogger - INFO - Subscription created successfully for user_id: 11e216bf-4770-4568-bf16-1105337170c7
2025-06-24 23:31:35,805 - backendlogger - INFO - data
2025-06-24 23:32:04,821 - backendlogger - INFO - subscription_updated
2025-06-24 23:32:05,025 - backendlogger - INFO - Subscription updated successfully for user_id: 11e216bf-4770-4568-bf16-1105337170c7
2025-06-24 23:32:05,026 - backendlogger - INFO - data
2025-06-24 23:33:20,779 - backendlogger - INFO - subscription_paused
2025-06-24 23:33:20,979 - backendlogger - INFO - Subscription paused successfully for paddle_subscription_id: 1293771
2025-06-24 23:33:20,979 - backendlogger - INFO - data
2025-06-24 23:33:20,995 - backendlogger - INFO - subscription_updated
2025-06-24 23:33:21,261 - backendlogger - INFO - Subscription updated successfully for user_id: 11e216bf-4770-4568-bf16-1105337170c7
2025-06-24 23:33:21,262 - backendlogger - INFO - data
2025-06-24 23:33:22,474 - backendlogger - INFO - subscription_updated
2025-06-24 23:33:22,864 - backendlogger - INFO - Subscription updated successfully for user_id: 11e216bf-4770-4568-bf16-1105337170c7
2025-06-24 23:33:22,864 - backendlogger - INFO - data
2025-06-24 23:33:36,350 - backendlogger - INFO - subscription_unpaused
2025-06-24 23:33:36,350 - backendlogger - INFO - data
2025-06-24 23:33:36,812 - backendlogger - INFO - subscription_updated
2025-06-24 23:33:37,013 - backendlogger - INFO - subscription_updated
2025-06-24 23:33:37,111 - backendlogger - INFO - Subscription updated successfully for user_id: 11e216bf-4770-4568-bf16-1105337170c7
2025-06-24 23:33:37,112 - backendlogger - INFO - data
2025-06-24 23:33:37,336 - backendlogger - INFO - Subscription updated successfully for user_id: 11e216bf-4770-4568-bf16-1105337170c7
2025-06-24 23:33:37,336 - backendlogger - INFO - data
2025-06-24 23:34:16,813 - backendlogger - INFO - subscription_cancelled
2025-06-24 23:34:16,987 - backendlogger - INFO - subscription_updated
2025-06-24 23:34:17,306 - backendlogger - INFO - Subscription cancelled successfully for paddle_subscription_id: 1293771
2025-06-24 23:34:17,355 - backendlogger - INFO - data
2025-06-24 23:34:17,934 - backendlogger - INFO - Subscription updated successfully for user_id: 11e216bf-4770-4568-bf16-1105337170c7
2025-06-24 23:34:17,934 - backendlogger - INFO - data
2025-06-24 23:34:18,099 - backendlogger - INFO - subscription_updated
2025-06-24 23:34:18,483 - backendlogger - INFO - Subscription updated successfully for user_id: 11e216bf-4770-4568-bf16-1105337170c7
2025-06-24 23:34:18,483 - backendlogger - INFO - data
2025-06-24 23:34:30,678 - backendlogger - INFO - subscription_resumed
2025-06-24 23:34:30,678 - backendlogger - INFO - data
2025-06-24 23:34:30,680 - backendlogger - INFO - subscription_updated
2025-06-24 23:34:30,998 - backendlogger - INFO - Subscription updated successfully for user_id: 11e216bf-4770-4568-bf16-1105337170c7
2025-06-24 23:34:30,999 - backendlogger - INFO - data
2025-06-24 23:34:31,614 - backendlogger - INFO - subscription_updated
2025-06-24 23:34:32,234 - backendlogger - INFO - Subscription updated successfully for user_id: 11e216bf-4770-4568-bf16-1105337170c7
2025-06-24 23:34:32,234 - backendlogger - INFO - data
